### ISSUE TITLE
Axis Labels wrong value

### ISSUE THREAD

**Issue by bb-git** [litoarias/HACBarChart#2]
It is really working great now :). I got it looking like I was expecting, only the labels at the X-Axis are strange. See the image.
![bildschirmfoto 2016-01-15 um 20 02 48](https://cloud.githubusercontent.com/assets/7348507/12362408/74ae2de4-bbc3-11e5-88ba-07cb4129a680.png)

This is the array I initialize the chart with:
(
        {
        color = "UIDeviceRGBColorSpace 0.293333 0.332157 0.094902 0.8";
        customText = Me;
        percentage = 500;
    },
        {
        color = "UIDeviceRGBColorSpace 0.293333 0.332157 0.094902 0.64";
        customText = anna;
        percentage = 1500;
    },
        {
        color = "UIDeviceRGBColorSpace 0.293333 0.332157 0.094902 0.48";
        customText = egon;
        percentage = 800;
    },
        {
        color = "UIDeviceRGBColorSpace 0.293333 0.332157 0.094902 0.32";
        customText = hans;
        percentage = 1000;
    },
        {
        color = "UIDeviceRGBColorSpace 0 0.62 0.89 0.8";
        customText = Me;
        percentage = 100;
    },
        {
        color = "UIDeviceRGBColorSpace 0 0.62 0.89 0.84";
        customText = anna;
        percentage = 400;
    },
        {
        color = "UIDeviceRGBColorSpace 0 0.62 0.89 0.68";
        customText = egon;
        percentage = 300;
    },
        {
        color = "UIDeviceRGBColorSpace 0 0.62 0.89 0.52";
        customText = hans;
        percentage = 200;
    }
)

**Comment by litoarias** [comment]
Whenever I get time, I check failure! Thnx for this review

**Comment by bb-git** [comment]
Thank you for these great charts :)
I change line 403: j to i and removed the digit from the string
text = [NSString stringWithFormat:@"%.0f",(float)((_axisMaxValue / divider))*i];

**Comment by litoarias** [comment]
Thanks for your contribution, project it's updated! :+1:
