### ISSUE TITLE
wrong values in y-axis labels

### ISSUE THREAD

**Issue by LenasL** [litoarias/HACBarChart#3]
Thanks for the really nice bar charts! Unfortunatly the y axis values are sometimes completly wrong. For example the values of the last bar is 1304, but it seems to be smaller than 1288. Please help me!
![img_0005](https://cloud.githubusercontent.com/assets/23438917/20248582/7db17bae-a9e7-11e6-9447-764c5e93e5d8.PNG)

**Comment by LenasL** [comment]
Solution: you need setup the y axis numbers with _axisMaxValue / (divider-1) instead of _axisMaxValue / divider (lines 426 and 484). Tried to create a branch with the bug fix, but got a 403 error.

**Comment by litoarias** [comment]
The repo it`s updated. thnxs for contribute
