### ISSUE TITLE
Incorrect title for Y lables.

### ISSUE THREAD

**Issue by ilosqut** [litoarias/HACBarChart#4]
Text for Y title labels is incorrect.
Please check calculations, Here is an example:
![11111](https://cloud.githubusercontent.com/assets/909903/20628461/1c959c7a-b337-11e6-9e1d-93d9c878cfc4.png)

Added by this commit:
https://github.com/litoarias/HACBarChart/commit/d45096523982b2bb73f0acf63b7608af1ec2e3b2

**Comment by luka1995** [comment]
I have also that problem... I think problem is in method: setupAxisYNumbers.

**Comment by luka1995** [comment]
@litoarias Can you check?

**Comment by luka1995** [comment]
<img width="338" alt="screen shot 2016-12-03 at 16 55 17" src="https://cloud.githubusercontent.com/assets/3648001/20860471/4ac28e4e-b979-11e6-9553-99197111bf1f.png">
I need to have values from 0, 10, 20, 30 to 100.0

**Comment by PriyaCE** [comment]
Hello,

In "HACBarChart.m" file, replace number of line 448 ( lbl.text = text;) with below text

CGFloat MaxValue = (float)[self getMaxValue] + 1;
CGFloat gapValue = MaxValue /(_numberDividersAxisY - 1);
lbl.text = [NSString stringWithFormat:@"%.1f", j*gapValue];

I hope that will works !

**Comment by priyace5** [comment]
Hello @ilosqut ,

In "HACBarChart.m" , Line number 448 (lbl.text = text;) replace with below text

CGFloat MaxValue = (float)[self getMaxValue] + 1;
CGFloat gapValue = MaxValue /(_numberDividersAxisY - 1);
lbl.text = [NSString stringWithFormat:@"%.1f", j*gapValue];

**Comment by ilosqut** [comment]
@PriyaCE I replaced this lib with charts)). This lib has too many bugs.

**Comment by litoarias** [comment]
Under title I wrote **Attention, this project is without maintenance**, thanks
